Imports System.Data.SqlClient
Public Class ClsFatcaAccMaster
    Protected Friend Function lFnSearchAccMaster(ByVal accNo As String, ByVal accName As String, ByVal brid As String, ByVal ccdref As String, personID As String) As DataSet
        Dim ds As New DataSet

        Dim condList As New List(Of String)
        Dim accSqlStr As String = String.Empty

        accSqlStr += " SELECT"
        accSqlStr += "    Account_No,"
        accSqlStr += "    Account_Name,"
        accSqlStr += "    client_type,"
        accSqlStr += "    Client_Nature,"
        accSqlStr += "    BR_ID,"
        accSqlStr += "    AE_No,"
        accSqlStr += "    Branch,"
        accSqlStr += "    PersonID,"
        accSqlStr += "    CCD_REF,"
        accSqlStr += "    FATCA_GIIN,"
        accSqlStr += "    FATCA_Account_Type,"
        accSqlStr += "    US_in_care_of_or_hold_mail_address,"
        accSqlStr += "    US_Citizen,"
        accSqlStr += "    Born_in_US,"
        accSqlStr += "    US_Address,"
        accSqlStr += "    US_Telephone_No,"
        accSqlStr += "    Fund_Transfer_US,"
        accSqlStr += "    Authorized_person_with_US_address,"
        accSqlStr += "    W_form_signed,"
        accSqlStr += "    Date_of_Signings,"
        accSqlStr += "    TIN,"
        accSqlStr += "    Last_Review_Date,"
        accSqlStr += "    FATCA_Remarks"
        accSqlStr += " FROM"
        accSqlStr += " ("
        accSqlStr += " SELECT"
        accSqlStr += "    sec_table.accno AS Account_No,"
        accSqlStr += "    sec_table.name_1 AS Account_Name,"
        accSqlStr += "    sec_table.client_type AS client_type,"
        accSqlStr += "    ISNULL(sec_table.nature_s, '') AS Client_Nature,"
        accSqlStr += "    ISNULL(sec_table.br_id, '') AS BR_ID,"
        accSqlStr += "    sec_table.aeno AS AE_No,"
        accSqlStr += "    sec_table.branch_name AS Branch,"
        accSqlStr += "    ISNULL(convert (varchar, cm.PersonID ),'') AS PersonID,"
        accSqlStr += "    ISNULL(convert (varchar, cm.ccd_ref ),'') AS CCD_REF,"
        accSqlStr += "    ISNULL(cm.FATCA_GIIN, '') AS FATCA_GIIN,"
        accSqlStr += "    ISNULL(cm.FATCA_acc_type, '') AS FATCA_Account_Type,"
        accSqlStr += "    ISNULL(cm.us_passport_holder, '') AS US_in_care_of_or_hold_mail_address,"
        accSqlStr += "    ISNULL(cm.us_citizen, '') AS US_Citizen,"
        accSqlStr += "    ISNULL(cm.us_born, '') AS Born_in_US,"
        accSqlStr += "    ISNULL(cm.us_address, '') AS US_Address,"
        accSqlStr += "    ISNULL(cm.us_phone, '') AS US_Telephone_No,"
        accSqlStr += "    ISNULL(cm.us_fund_transfer, '') AS Fund_Transfer_US,"
        accSqlStr += "    ISNULL(cm.us_auth_person, '') AS Authorized_person_with_US_address,"
        accSqlStr += "    ISNULL(cm.w8_form_signed, '') AS W_form_signed,"
        accSqlStr += "    CASE"
        accSqlStr += "       WHEN CONVERT (varchar(30), ISNULL(cm.w8_form_date, ''), 103 ) ='01/01/1900' THEN ''"
        accSqlStr += "       ELSE CONVERT (varchar(30), ISNULL(cm.w8_form_date, ''), 103 )"
        accSqlStr += "    END AS Date_of_Signings,"
        accSqlStr += "    ISNULL(cm.us_tin, '') AS TIN,"
        accSqlStr += "    CASE"
        accSqlStr += "       WHEN CONVERT (varchar(30), ISNULL(cm.us_review_date, ''), 103 ) ='01/01/1900' THEN ''"
        accSqlStr += "       ELSE CONVERT (varchar(30), ISNULL(cm.us_review_date, ''), 103 )"
        accSqlStr += "    END AS Last_Review_Date,"
        accSqlStr += "    ISNULL(cm.FATCA_Remarks, '') AS FATCA_Remarks"
        accSqlStr += " FROM"
        accSqlStr += " ("
        accSqlStr += "  SELECT"
        accSqlStr += "    scm.accno,"
        accSqlStr += "    scm.name_1,"
        accSqlStr += "    CASE"
        accSqlStr += "       WHEN SUBSTRING (scm.accno, 1 ,3) = '500' THEN 'CIES'"
        accSqlStr += "       ELSE 'Securities'"
        accSqlStr += "       END AS client_type,"
        accSqlStr += "    CASE scm.nature"
        accSqlStr += "       WHEN '0' THEN 'Individual' WHEN '1' THEN 'Joint'"
        accSqlStr += "       ELSE 'Corporation'"
        accSqlStr += "       END AS nature_s,"
        accSqlStr += "    scm.br_id,"
        accSqlStr += "    ae.aeno,"
        accSqlStr += "    bm.name AS branch_name"
        accSqlStr += "  FROM " & GStrG2BSDB & ".dbo.client_master scm"
        accSqlStr += "  LEFT JOIN " & GStrG2BSDB & ".dbo.client_master_s scms"
        accSqlStr += "  ON scm.aid = scms.aid"
        accSqlStr += "  left join " & GStrG2BSDB & ".dbo.ae_master ae"
        accSqlStr += "  ON ae.aeid = scms.aeid and ae.cmid = scms.cmid"
        accSqlStr += "  left join " & GStrG2BSDB & ".dbo.branch_master bm"
        accSqlStr += "  ON bm.cmid = scms.cmid and bm.bhid = scms.bhid"
        accSqlStr += " ) sec_table"
        accSqlStr += " LEFT JOIN"
        accSqlStr += " ("
        accSqlStr += "   SELECT"
        accSqlStr += "     acc_no,"
        accSqlStr += "     PersonID,"
        accSqlStr += "     ccd_ref,"
        accSqlStr += "     FATCA_GIIN,"
        accSqlStr += "     FATCA_acc_type,"
        accSqlStr += "     us_passport_holder,"
        accSqlStr += "     us_citizen,"
        accSqlStr += "     us_born,"
        accSqlStr += "     us_address,"
        accSqlStr += "     us_phone,"
        accSqlStr += "     us_fund_transfer,"
        accSqlStr += "     us_auth_person,"
        accSqlStr += "     w8_form_signed,"
        accSqlStr += "     w8_form_date,"
        accSqlStr += "     us_tin,"
        accSqlStr += "     us_review_date,"
        accSqlStr += "     FATCA_Remarks"
        accSqlStr += "   FROM dbo.client_master"
        accSqlStr += "   WHERE client_type = 'Securities' or client_type = 'CIES'"
        accSqlStr += " ) cm"
        accSqlStr += " ON sec_table.accno collate Chinese_Taiwan_Stroke_CI_AS = cm.acc_no"
        accSqlStr += " UNION"
        accSqlStr += " SELECT"
        accSqlStr += "    fut_table.accno AS Account_No,"
        accSqlStr += "    fut_table.name_1 AS Account_Name,"
        accSqlStr += "    fut_table.client_type As client_type,"
        accSqlStr += "    ISNULL(fut_table.nature_s, '') AS Client_Nature,"
        accSqlStr += "    ISNULL(fut_table.br_id, '') AS BR_ID,"
        accSqlStr += "    fut_table.aeno AS AE_No,"
        accSqlStr += "    fut_table.branch_name AS Branch,"
        accSqlStr += "    ISNULL(convert (varchar, cm.PersonID ),'') AS PersonID,"
        accSqlStr += "    ISNULL(convert (varchar, cm.ccd_ref ),'') AS CCD_REF,"
        accSqlStr += "    ISNULL(cm.FATCA_GIIN, '') AS FATCA_GIIN,"
        accSqlStr += "    ISNULL(cm.FATCA_acc_type, '') AS FATCA_Account_Type,"
        accSqlStr += "    ISNULL(cm.us_passport_holder, '') AS US_in_care_of_or_hold_mail_address,"
        accSqlStr += "    ISNULL(cm.us_citizen, '') AS US_Citizen,"
        accSqlStr += "    ISNULL(cm.us_born, '') AS Born_in_US,"
        accSqlStr += "    ISNULL(cm.us_address, '') AS US_Address,"
        accSqlStr += "    ISNULL(cm.us_phone, '') AS US_Telephone_No,"
        accSqlStr += "    ISNULL(cm.us_fund_transfer, '') AS Fund_Transfer_US,"
        accSqlStr += "    ISNULL(cm.us_auth_person, '') AS Authorized_person_with_US_address,"
        accSqlStr += "    ISNULL(cm.w8_form_signed, '') AS W_form_signed,"
        accSqlStr += "    CASE"
        accSqlStr += "      WHEN CONVERT (VARCHAR(30), ISNULL(cm.w8_form_date, ''), 103 ) ='01/01/1900' THEN ''"
        accSqlStr += "      ELSE CONVERT (VARCHAR(30), ISNULL(cm.w8_form_date, ''), 103 )"
        accSqlStr += "    END AS Date_of_Signings,"
        accSqlStr += "    ISNULL(cm.us_tin, '') AS TIN,"
        accSqlStr += "    CASE"
        accSqlStr += "      WHEN CONVERT (VARCHAR(30), ISNULL(cm.us_review_date, ''), 103 ) ='01/01/1900' THEN ''"
        accSqlStr += "      ELSE CONVERT (VARCHAR(30), ISNULL(cm.us_review_date, ''), 103 )"
        accSqlStr += "    END AS Last_Review_Date,"
        accSqlStr += "    ISNULL(cm.FATCA_Remarks, '') AS FATCA_Remarks"
        accSqlStr += " FROM"
        accSqlStr += " ("
        accSqlStr += " SELECT"
        accSqlStr += "     fcm.accno,"
        accSqlStr += "     CAST(fcm.name_1 AS NVARCHAR(60)) AS name_1,"
        accSqlStr += "     CASE"
        accSqlStr += "        WHEN SUBSTRING (fcm.accno, 1 ,3) = '500' THEN 'CIES'"
        accSqlStr += "        ELSE 'Futures'"
        accSqlStr += "        END AS client_type,"
        accSqlStr += "     CASE fcm.nature"
        accSqlStr += "        WHEN '0' THEN 'Individual'"
        accSqlStr += "        WHEN '1' THEN 'Joint'"
        accSqlStr += "        ELSE 'Corporation'"
        accSqlStr += "     END AS nature_s,"
        accSqlStr += "     fcm.br_id,"
        accSqlStr += "     ae.aeno,"
        accSqlStr += "     bm.name as branch_name"
        accSqlStr += " FROM " & GStrG2BFDB & ".dbo.client_master fcm"
        accSqlStr += " LEFT JOIN " & GStrG2BFDB & ".dbo.client_master_f fcms"
        accSqlStr += " ON fcm.aid = fcms.aid"
        accSqlStr += " LEFT JOIN " & GStrG2BFDB & ".dbo.ae_master ae"
        accSqlStr += " ON ae.aeid = fcms.aeid and ae.cmid = fcms.cmid"
        accSqlStr += " LEFT JOIN " & GStrG2BFDB & ".dbo.branch_master bm"
        accSqlStr += " ON bm.cmid = fcms.cmid and bm.bhid = fcms.bhid"
        accSqlStr += " ) fut_table"
        accSqlStr += " LEFT JOIN"
        accSqlStr += " ("
        accSqlStr += "  SELECT"
        accSqlStr += "     acc_no,"
        accSqlStr += "     PersonID,"
        accSqlStr += "     ccd_ref,"
        accSqlStr += "     FATCA_GIIN,"
        accSqlStr += "     FATCA_acc_type,"
        accSqlStr += "     us_passport_holder,"
        accSqlStr += "     us_citizen,"
        accSqlStr += "     us_born,"
        accSqlStr += "     us_address,"
        accSqlStr += "     us_phone,"
        accSqlStr += "     us_fund_transfer,"
        accSqlStr += "     us_auth_person,"
        accSqlStr += "     w8_form_signed,"
        accSqlStr += "     w8_form_date,"
        accSqlStr += "     us_tin,"
        accSqlStr += "     us_review_date,"
        accSqlStr += "     FATCA_Remarks"
        accSqlStr += "  FROM dbo.client_master"
        accSqlStr += "  WHERE client_type = 'Futures' or client_type = 'CIES'"
        accSqlStr += " ) as cm"
        accSqlStr += " ON fut_table.accno collate Chinese_Taiwan_Stroke_CI_AS = cm.acc_no"
        accSqlStr += " ) secfut_master "

        If Not String.IsNullOrEmpty(accNo) Then condList.Add("secfut_master.Account_No like '%" & accNo & "%'")
        If Not String.IsNullOrEmpty(accName) Then condList.Add("secfut_master.Account_Name like '%" & accName & "%'")
        If Not String.IsNullOrEmpty(brid) Then condList.Add("secfut_master.BR_ID like '%" & brid & "%'")
        If Not String.IsNullOrEmpty(ccdref) Then condList.Add("secfut_master.CCD_REF = " & ccdref)
        If Not String.IsNullOrEmpty(personID) Then condList.Add("secfut_master.PersonID = " & personID)

        If condList.Count <> 0 Then
            Const joinAnd As String = " and "
            accSqlStr += "where "
            For Each c As String In condList
                accSqlStr += c + joinAnd
            Next
            accSqlStr = accSqlStr.Substring(0, accSqlStr.Length - joinAnd.Length)             'trim tail and keyword
        End If

        ds = GFncRtnDS(GSCnSqlConn, accSqlStr, "cltMaster")
        Return ds
    End Function
End Class
