USE [ESL]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tmp_client_master_2](
	[accno] [char](20) NOT NULL,
	[nature_s] [varchar](11) NOT NULL,
	[client_type] [varchar](10) NOT NULL,
	[name_1] [nvarchar](60) NULL,
	[name_1_c] [nvarchar](60) NULL,
	[aeno] [char](20) NULL,
	[br_id] [char](40) NULL,
	[date_open] [datetime] NULL,
	[sus_date] [datetime] NULL,
	[suspend_field] [varchar](3) NOT NULL,
	[suspend_code] [varchar](40) NULL,
	[date_close] [datetime] NULL,
	[external_accno] [varchar](10) NULL,
	[date_renew] [datetime] NULL,
	[dob] [datetime] NULL,
	[external_credit_lmt] [money] NULL,
	[memo] [nvarchar](3000) NULL,
	[CBT] [varchar](3) NOT NULL,
	[CJCE] [varchar](3) NOT NULL,
	[CME] [varchar](3) NOT NULL,
	[CMX] [varchar](3) NOT NULL,
	[HKEX] [varchar](3) NOT NULL,
	[LME] [varchar](3) NOT NULL,
	[NYM] [varchar](3) NOT NULL,
	[NYB] [varchar](3) NOT NULL,
	[TGE] [varchar](3) NOT NULL,
	[TOCOM] [varchar](3) NOT NULL,
	[aid] [char](10) NULL,
	[SEHK] [varchar](3) NULL,
	[SZEN] [varchar](3) NULL,
	[TF] [varchar](3) NULL,
	[CBUS] [varchar](3) NULL,
	[CBHK] [varchar](3) NULL,
	[SG] [varchar](3) NULL,
	[SSE] [varchar](3) NULL,
	[BDHK] [varchar](3) NULL,
	[FUND] [varchar](3) NULL,
	[US] [varchar](3) NULL,
	[BDCN] [varchar](3) NULL,
	[MAMK] [varchar](3) NULL,
	[ae_name] [char](40) NOT NULL,
	[ae_email] [char](40) NULL,
	[branch_name] [varchar](60) NOT NULL,
	[ccd_ref] [int] NULL,
	[market] [nvarchar](100) NULL,
	[acc_status] [nvarchar](10) NULL,
	[is_dormant] [nvarchar](1) NULL,
	[br_id_2] [nvarchar](30) NULL,
	[auth_remark] [nvarchar](1000) NULL,
	[joint_relationship] [nvarchar](50) NULL,
	[joint_name] [nvarchar](50) NULL,
	[joint_br_id] [nvarchar](30) NULL,
	[joint_br_id_2] [nvarchar](30) NULL,
	[joint_gender_s] [nvarchar](10) NULL,
	[joint_dob] [datetime] NULL,
	[nationality_1] [nvarchar](50) NULL,
	[nationality_2] [nvarchar](50) NULL,
	[occupation_1] [nvarchar](50) NULL,
	[occupation_1_other] [nvarchar](50) NULL,
	[occupation_2] [nvarchar](50) NULL,
	[occupation_2_other] [nvarchar](50) NULL,
	[place_of_incorp] [nvarchar](50) NULL,
	[business_nature] [nvarchar](50) NULL,
	[correspondence] [nvarchar](20) NULL,
	[country_code] [nvarchar](3) NULL,
	[staff_acc] [nvarchar](1) NULL,
	[related_margin_acc] [nvarchar](50) NULL,
	[other_licensed_corp] [nvarchar](1) NULL,
	[related_acc_remark] [nvarchar](1000) NULL,
	[aiml_risk] [nvarchar](50) NULL,
	[high_risk_category] [nvarchar](50) NULL,
	[high_risk_category_other] [nvarchar](50) NULL,
	[high_risk_desc] [nvarchar](1000) NULL,
	[fund_source] [nvarchar](50) NULL,
	[fund_source_other] [nvarchar](50) NULL,
	[review_date] [datetime] NULL,
	[gross_income] [nvarchar](1) NULL,
	[net_asset_value] [nvarchar](1) NULL,
	[invest_objective] [nvarchar](50) NULL,
	[invest_experience] [nvarchar](1) NULL,
	[invest_time_frame] [nvarchar](50) NULL,
	[sum_to_invest] [numeric](18, 2) NULL,
	[professional_investor] [nvarchar](10) NULL,
	[risk_tolerance] [nvarchar](1) NULL,
	[RPQ_complete_date] [datetime] NULL,
	[know_derivative] [nvarchar](1) NULL,
	[FATCA_acc_type] [nvarchar](30) NULL,
	[FATCA_GIIN] [nvarchar](19) NULL,
	[w8_form_signed] [nvarchar](1) NULL,
	[w8_form_date] [datetime] NULL,
	[us_passport_holder] [nvarchar](1) NULL,
	[us_citizen] [nvarchar](1) NULL,
	[us_born] [nvarchar](1) NULL,
	[us_address] [nvarchar](1) NULL,
	[us_phone] [nvarchar](1) NULL,
	[us_fund_transfer] [nvarchar](1) NULL,
	[us_auth_person] [nvarchar](1) NULL,
	[us_review_date] [datetime] NULL,
	[non_face_to_face] [nvarchar](1) NULL,
	[us_tin] [nvarchar](50) NULL,
	[w8_form_expiry_date] [datetime] NULL,
	[FATCA_Remarks] [nvarchar](300) NULL
) ON [PRIMARY]

GO


