'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ESL.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Number.
        '''</summary>
        Friend ReadOnly Property AccountNo() As String
            Get
                Return ResourceManager.GetString("AccountNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property all_caution() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("all_caution", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property all_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("all_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property all_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("all_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Branch.
        '''</summary>
        Friend ReadOnly Property Branch() As String
            Get
                Return ResourceManager.GetString("Branch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDelete_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDelete_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnDetails_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnDetails_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnEdit_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnEdit_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnNew_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnNew_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnSort_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnSort_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to date_close.
        '''</summary>
        Friend ReadOnly Property date_close() As String
            Get
                Return ResourceManager.GetString("date_close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to date_suspend.
        '''</summary>
        Friend ReadOnly Property date_suspend() As String
            Get
                Return ResourceManager.GetString("date_suspend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date Open.
        '''</summary>
        Friend ReadOnly Property DateOpen() As String
            Get
                Return ResourceManager.GetString("DateOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOY.
        '''</summary>
        Friend ReadOnly Property DOB() As String
            Get
                Return ResourceManager.GetString("DOB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document-new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document-save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit-delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_but_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_but_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_but_guide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_but_guide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_but_hk_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_but_hk_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_but_install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_but_install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_login_demo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_login_demo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_pw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_pw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_subtitle_global_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_subtitle_global_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_subtitle_local_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_subtitle_local_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_subtitle_password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_subtitle_password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_subtitle_spec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_subtitle_spec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_title_platform_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_title_platform_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_title_platform_install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_title_platform_install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_title_platform_login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_title_platform_login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_title_platform_operation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_title_platform_operation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gender.
        '''</summary>
        Friend ReadOnly Property Gender() As String
            Get
                Return ResourceManager.GetString("Gender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Emperor Futures Limited - Password Notification Letter&lt;/title&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=big5&quot;&gt;
        '''&lt;style&gt;
        '''td {color: #000000}
        '''&lt;/style&gt;
        '''&lt;base target=&quot;_blank&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;#FFFFFF&quot;&gt;
        '''&lt;p&gt;&lt;center&gt;&lt;img src=cid:all_logo&gt;&lt;/center&gt;&lt;hr&gt;
        '''&lt;font size=&quot;2&quot; face=&quot;arial&quot;&gt;
        '''&lt;p&gt;Dear %USERNAME%,
        '''&lt;p&gt;Thanks very much for opening an online futures trading account in our company. For your kind information, the following is the instruction related to usin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property htmlE() As String
            Get
                Return ResourceManager.GetString("htmlE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;head&gt;
        '''&lt;title&gt;英皇期货有限公司 - 网上密码通知书&lt;/title&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=gb2312&quot;&gt;
        '''&lt;style&gt;
        '''td {color: #000000}
        '''&lt;/style&gt;
        '''&lt;base target=&quot;_blank&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;#FFFFFF&quot;&gt;
        '''&lt;p&gt;&lt;center&gt;&lt;img src=cid:all_logo&gt;&lt;/center&gt;&lt;hr&gt;
        '''&lt;font size=&quot;2&quot; face=&quot;arial&quot;&gt;
        '''&lt;p&gt;亲爱的%USERNAME%:
        '''&lt;p&gt;多谢你于本公司开设了网上期货交易户口，以下是关于本公司交易平台的指引。
        '''
        '''&lt;p&gt;&lt;img src=cid:sc_title_platform_dl&gt;
        '''&lt;br&gt;请先按以下按钮下载交易平台的安装程序。为确保能为阁下提供理想的下载速度，如阁下身在中国内地，请按&quot;中国下载&quot;，否则建议阁下按&quot;香港下载&quot;。&lt;br&gt;&lt;a href=&quot;http://emperorcapital.com/filemana [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property htmlS() As String
            Get
                Return ResourceManager.GetString("htmlS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;英皇期貨有限公司 - 網上密碼通知書&lt;/title&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=big5&quot;&gt;
        '''&lt;style&gt;
        '''td {color: #000000}
        '''&lt;/style&gt;
        '''&lt;base target=&quot;_blank&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;#FFFFFF&quot;&gt;
        '''&lt;p&gt;&lt;center&gt;&lt;img src=cid:all_logo&gt;&lt;/center&gt;&lt;hr&gt;
        '''&lt;font size=&quot;2&quot; face=&quot;arial&quot;&gt;
        '''&lt;p&gt;親愛的%USERNAME%:
        '''&lt;p&gt;多謝你於本公司開設了網上期貨交易戶口，以下是關於本公司交易平台的指引。
        '''
        '''&lt;p&gt;&lt;img src=cid:tc_title_platform_dl&gt;
        '''&lt;br&gt;請先按以下按鈕下載交易平台的安裝程式。為確保能為閣下提供理想的下載速度，如閣下身在中國內地，請按&quot;中國下載&quot;，否則建議閣下按&quot;香港下載&quot;。&lt;br&gt;&lt;a href=&quot;http://emperorcapital.com/fi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property htmlT() As String
            Get
                Return ResourceManager.GetString("htmlT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID/Passport ID.
        '''</summary>
        Friend ReadOnly Property IDPass() As String
            Get
                Return ResourceManager.GetString("IDPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nationality.
        '''</summary>
        Friend ReadOnly Property Nationality() As String
            Get
                Return ResourceManager.GetString("Nationality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear %USERNAME%, 
        '''
        '''Thanks very much for opening an online securities trading account in our company.
        '''
        '''-------------------------------------------------------------------------------
        '''
        '''Trading Platform Password 
        '''
        '''Your initial password: %TRADE_CODE% 
        '''
        '''Caution: Please go to securities part of &quot;Online Trading&quot; in www.emperorcapital.com. After the initial login of the platform, the password should be changed. The new password should contain at least 8 digitals and contain both english letter and number. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_eng_afe_only() As String
            Get
                Return ResourceManager.GetString("PN_template_eng_afe_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear %USERNAME%, 
        '''
        '''Thanks very much for opening an online securities trading account in our company.
        '''
        '''-------------------------------------------------------------------------------
        '''
        '''Trading Platform Password 
        '''
        '''Your initial password: %TRADE_CODE% 
        '''Caution: Please go to securities part of &quot;Online Trading&quot; in www.emperorcapital.com. After the initial login of the platform, the password should be changed. The new password should contain at least 8 digitals and contain both english letter and number.
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_eng_both() As String
            Get
                Return ResourceManager.GetString("PN_template_eng_both", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear %USERNAME%, 
        '''
        '''Thanks very much for opening an online securities trading account in our company.
        '''
        '''-------------------------------------------------------------------------------
        '''
        '''Trading Platform Password 
        '''
        '''Your initial password: %TRADE_CODE% 
        '''Caution: Please go to securities part of &quot;Online Trading&quot; in www.emperorcapital.com to download and install the platform. After the initial login of the platform, the password is recommended to be changed. The new password should contain 6 to 8 digitals.        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_eng_ttl_only() As String
            Get
                Return ResourceManager.GetString("PN_template_eng_ttl_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 亲爱的%USERNAME%: 
        '''
        '''多谢你于本公司开设了网上证券交易户口。
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密码
        '''
        '''阁下的平台初始密码为：%TRADE_CODE% 
        '''提示：请进入 www.emperorcapital.com 中 &quot;网上交易&quot; 的证券部分登入交易平台。首次登入平台后，须强制性更改密码。密码必须不少于8个字符，而包括英文字母及数目字。
        '''
        '''如阁下已开通了网上交易平台 及 闪电交易平台，两个平台已实施密码一体化方案。客户如在其中一方平台更新密码，便可实时以新密码登入另一平台。
        '''
        '''-------------------------------------------------------------------------------- 
        '''
        '''证券交易须知
        '''
        '''1. 交易时间 (香港时间)   
        '''开市前时段　　　　上午9时正至上午9时30分 
        '''早市　　　　　　　上午9时30分至中午12时正 
        '''午市　　　　　　　下午1时00分至 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_sc_afe_only() As String
            Get
                Return ResourceManager.GetString("PN_template_sc_afe_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 亲爱的%USERNAME%: 
        '''
        '''多谢你于本公司开设了网上证券交易户口。
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密码
        '''
        '''阁下的平台初始密码为：%TRADE_CODE% 
        '''
        '''提示：本公司已为阁下开设了网上交易平台，请进入 www.emperorcapital.com 中 &quot;网上交易&quot; 的证券部分登入交易平台。首次登入平台后，须强制性更改密码。密码必须不少于8个字符，而包括英文字母及数目字。
        '''
        '''本公司同时亦已为阁下开设了闪电交易平台，请进入 www.emperorcapital.com 中 &quot;网上交易&quot; 的证券部分下载 及 安装闪电交易平台。首次登入平台后，请立即更改密码。密码必须不少为6个至8个字符。
        '''
        '''为方便客户，本公司的网上交易平台 及 闪电交易平台，已实施密码一体化方案。客户如在其中一方平台更新密码，便可实时以新密码登入另一平台。
        '''
        '''------------------------------------------------------ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_sc_both() As String
            Get
                Return ResourceManager.GetString("PN_template_sc_both", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 亲爱的%USERNAME%: 
        '''
        '''多谢你于本公司开设了英皇证券闪电交易平台。
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密码
        '''
        '''阁下的平台初始密码为：%TRADE_CODE% 
        '''提示：请进入 www.emperorcapital.com 中 &quot;网上交易&quot; 的证券部分下载闪电交易平台。首次登入平台后，请立即更改密码。密码必须不少为6个至8个字符。
        '''
        '''如阁下已开通了网上交易平台 及 闪电交易平台，两个平台已实施密码一体化方案。客户如在其中一方平台更新密码，便可实时以新密码登入另一平台。
        '''
        '''-------------------------------------------------------------------------------- 
        '''
        '''证券交易须知
        '''
        '''1. 交易时间 (香港时间)   
        '''开市前时段　　　　上午9时正至上午9时30分 
        '''早市　　　　　　　上午9时30分至中午12时正 
        '''午市　　　　　　　下午1时00分至下午4时正  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_sc_ttl_only() As String
            Get
                Return ResourceManager.GetString("PN_template_sc_ttl_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 親愛的%USERNAME%: 
        '''
        '''多謝你於本公司開設了網上證券交易戶口。
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密碼
        '''
        '''閣下的平台初始密碼為：%TRADE_CODE% 
        '''提示：請進入 www.emperorcapital.com 中 &quot;網上交易&quot; 的證券部分登入交易平台。首次登入平台後，須強制性更改密碼。密碼必須不少於8個字元，而包括英文字母及數目字。
        '''
        '''如閣下已開通了網上交易平台 及 閃電交易平台，兩個平台已實施密碼一體化方案。客戶如在其中一方平台更新密碼，便可即時以新密碼登入另一平台。
        '''
        '''-------------------------------------------------------------------------------- 
        '''
        '''證券交易須知
        '''
        '''1. 交易時間 (香港時間)   
        '''開市前時段　　　　上午9時正至上午9時30分 
        '''早市　　　　　　　上午9時30分至中午12時正 
        '''午市　　　　　　　下午1時00分至 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_tc_afe_only() As String
            Get
                Return ResourceManager.GetString("PN_template_tc_afe_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 親愛的%USERNAME%: 
        '''
        '''多謝你於本公司開設了網上證券交易戶口。
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密碼
        '''
        '''閣下的平台初始密碼為：%TRADE_CODE% 
        '''
        '''提示：本公司已為閣下開設了網上交易平台，請進入 www.emperorcapital.com 中 &quot;網上交易&quot; 的證券部分登入交易平台。首次登入平台後，須強制性更改密碼。密碼必須不少於8個字元，而包括英文字母及數目字。
        '''
        '''本公司同時亦已為閣下開設了閃電交易平台，請進入 www.emperorcapital.com 中 &quot;網上交易&quot; 的證券部分下載 及 安裝閃電交易平台。首次登入平台後，請立即更改密碼。密碼必須不少為6個至8個字元。
        '''
        '''為方便客戶，本公司的網上交易平台 及 閃電交易平台，已實施密碼一體化方案。客戶如在其中一方平台更新密碼，便可即時以新密碼登入另一平台。
        '''
        '''------------------------------------------------------ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_tc_both() As String
            Get
                Return ResourceManager.GetString("PN_template_tc_both", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 親愛的%USERNAME%: 
        '''
        '''多謝你於本公司開設了英皇證券閃電交易平台。
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密碼
        '''
        '''閣下的平台初始密碼為：%TRADE_CODE% 
        '''提示：請進入 www.emperorcapital.com 中 &quot;網上交易&quot; 的證券部分下載閃電交易平台。首次登入平台後，請立即更改密碼。密碼必須不少為6個至8個字元。
        '''
        '''如閣下已開通了網上交易平台 及 閃電交易平台，兩個平台已實施密碼一體化方案。客戶如在其中一方平台更新密碼，便可即時以新密碼登入另一平台。
        '''
        '''-------------------------------------------------------------------------------- 
        '''
        '''證券交易須知
        '''
        '''1. 交易時間 (香港時間)   
        '''開市前時段　　　　上午9時正至上午9時30分 
        '''早市　　　　　　　上午9時30分至中午12時正 
        '''午市　　　　　　　下午1時00分至下午4時正  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PN_template_tc_ttl_only() As String
            Get
                Return ResourceManager.GetString("PN_template_tc_ttl_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emperor Futures Limited - Online Futures Trading Platform Password Notification.
        '''</summary>
        Friend ReadOnly Property pwdEmailSubE() As String
            Get
                Return ResourceManager.GetString("pwdEmailSubE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 英皇期货有限公司 - 网上期货交易平台密码通知.
        '''</summary>
        Friend ReadOnly Property pwdEmailSubS() As String
            Get
                Return ResourceManager.GetString("pwdEmailSubS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 英皇期貨有限公司 - 網上期貨交易平台密碼通知.
        '''</summary>
        Friend ReadOnly Property pwdEmailSubT() As String
            Get
                Return ResourceManager.GetString("pwdEmailSubT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_but_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_but_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_but_guide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_but_guide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_but_hk_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_but_hk_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_but_install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_but_install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_login_demo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_login_demo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_pw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_pw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_subtitle_global_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_subtitle_global_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_subtitle_local_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_subtitle_local_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_subtitle_password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_subtitle_password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_subtitle_spec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_subtitle_spec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_title_platform_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_title_platform_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_title_platform_install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_title_platform_install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_title_platform_login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_title_platform_login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sc_title_platform_operation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sc_title_platform_operation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emperor Securities Limited - Online Securities Trading Platform Password Notification.
        '''</summary>
        Friend ReadOnly Property SecPwdEmailSubE() As String
            Get
                Return ResourceManager.GetString("SecPwdEmailSubE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 英皇证券(香港)有限公司 - 网上证券交易平台密码通知.
        '''</summary>
        Friend ReadOnly Property SecPwdEmailSubS() As String
            Get
                Return ResourceManager.GetString("SecPwdEmailSubS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 英皇證券(香港)有限公司 - 網上證券交易平台密碼通知.
        '''</summary>
        Friend ReadOnly Property SecPwdEmailSubT() As String
            Get
                Return ResourceManager.GetString("SecPwdEmailSubT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear %USERNAME%, 
        '''
        '''Thanks very much for opening an online securities trading account in our company.
        '''
        '''-------------------------------------------------------------------------------
        '''
        '''Trading Platform Password 
        '''
        '''Your initial password: %TRADE_CODE% 
        '''Caution: Please go to securities part of &quot;Online Trading&quot; in www.emperor717.com. After the initial login of the platform, the password should be changed. The new password should contain at least 8 digitals and contain both english letter and number.
        '''
        '''-- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property secTextE() As String
            Get
                Return ResourceManager.GetString("secTextE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 亲爱的%USERNAME%: 
        '''
        '''多谢你于本公司开设了网上证券交易户口。        '''
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密码
        '''
        '''阁下的平台初始密码为：%TRADE_CODE% 
        '''提示：请进入 www.emperor717.com 中 &quot;网上交易&quot; 的证券部分登入交易平台。首次登入平台后，须强制性更改密码。密码必须不少于8个字符，而包括英文字母及数目字。        '''
        '''
        '''-------------------------------------------------------------------------------- 
        '''
        '''证券交易须知
        '''
        '''1. 交易时间 (香港时间)   
        '''开市前时段　　　　上午9时30分至上午10时正 
        '''早市　　　　　　　上午10时正至中午12时30分 
        '''午市　　　　　　　下午2时30分至下午4时正 
        '''(香港假期及特别情况除外) 
        '''
        '''2. 贵客户可致电客户服务部或通过网上交易系统执行买卖指令。　贵客户在交易平台下单后，可以致 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property secTextS() As String
            Get
                Return ResourceManager.GetString("secTextS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 親愛的%USERNAME%: 
        '''
        '''多謝你於本公司開設了網上證券交易戶口。        '''
        '''
        '''--------------------------------------------------------------------------------
        '''
        '''交易平台密碼
        '''
        '''閣下的平台初始密碼為：%TRADE_CODE% 
        '''提示：請進入 www.emperor717.com 中 &quot;網上交易&quot; 的證券部分登入交易平台。首次登入平台後，須強制性更改密碼。密碼必須不少於8個字元，而包括英文字母及數目字。        '''
        '''
        '''-------------------------------------------------------------------------------- 
        '''
        '''證券交易須知
        '''
        '''1. 交易時間 (香港時間)   
        '''開市前時段　　　　上午9時30分至上午10時正 
        '''早市　　　　　　　上午10時正至中午12時30分 
        '''午市　　　　　　　下午2時30分至下午4時正 
        '''(香港假期及特別情況除外) 
        '''
        '''2. 貴客戶可致電客戶服務部或通過網上交易系統執行買賣指令。　貴客戶在交易平台下單後，可以致 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property secTextT() As String
            Get
                Return ResourceManager.GetString("secTextT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to suspend_code.
        '''</summary>
        Friend ReadOnly Property suspend_code() As String
            Get
                Return ResourceManager.GetString("suspend_code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to suspend_field.
        '''</summary>
        Friend ReadOnly Property suspend_field() As String
            Get
                Return ResourceManager.GetString("suspend_field", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property system_log_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("system-log-out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_ae() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_ae", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_but_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_but_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_but_guide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_but_guide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_but_hk_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_but_hk_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_but_install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_but_install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_login_demo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_login_demo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_pw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_pw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_subtitle_global_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_subtitle_global_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_subtitle_local_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_subtitle_local_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_subtitle_password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_subtitle_password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_subtitle_spec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_subtitle_spec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_title_platform_dl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_title_platform_dl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_title_platform_install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_title_platform_install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_title_platform_login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_title_platform_login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tc_title_platform_operation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tc_title_platform_operation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear %USERNAME%, 
        '''
        '''Thanks very much for opening an online futures trading account in our company. For your kind information, the following is the instruction related to using our trading platform. 
        '''
        '''1. Download 
        '''Please download the installation file of trading platform by clicking the following buttons. In order to ensure a satisfactory downloading speed, please click the button of &quot;CN Download&quot; if you are currently in China. Otherwises, please click the button of &quot;HK Download&quot;.
        '''HK Download: http://em [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property textE() As String
            Get
                Return ResourceManager.GetString("textE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 亲爱的%USERNAME%: 
        '''
        '''多谢你于本公司开设了网上期货交易户口，以下是关于本公司交易平台的指引。 
        '''
        '''1. 平台下载 
        '''请先按以下按钮下载交易平台的安装程序。为确保能为阁下提供理想的下载速度，如阁下身在中国内地，请按&quot;中国下载&quot;，否则建议阁下按&quot;香港下载&quot;。
        '''香港下载: http://emperorcapital.com/filemanager/common/sptrader_r846/sptrader_emp_setup_r846.exe
        '''中国下载: http://emperorcapital.com/filemanager/common/sptrader_r846/sptrader_emp_setup_r846.exe
        '''
        '''2. 安装平台 
        '''请参阅以下安装说明。 
        '''安装说明: http://www.sharppoint.com.hk/chs/main/download_main.htm
        '''
        '''3. 登入平台
        '''安装平台后，点击桌面上的sptrader图示后，根据以下所示登入平台。 
        ''' 
        '''网域: 220.241.155.37 
        '''使用者: 阁下的客户编号 
        '''密码: 请参阅此 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property textS() As String
            Get
                Return ResourceManager.GetString("textS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 親愛的%USERNAME%: 
        '''
        '''多謝你於本公司開設了網上期貨交易戶口，以下是關於本公司交易平台的指引。 
        '''
        '''1. 平台下載 
        '''請先按以下按鈕下載交易平台的安裝程式。為確保能為閣下提供理想的下載速度，如閣下身在中國內地，請按&quot;中國下載&quot;，否則建議閣下按&quot;香港下載&quot;。
        '''香港下載: http://emperorcapital.com/filemanager/common/sptrader_r846/sptrader_emp_setup_r846.exe
        '''中國下載: http://emperorcapital.com/filemanager/common/sptrader_r846/sptrader_emp_setup_r846.exe
        '''
        '''2. 安裝平台 
        '''請參閱以下安裝說明。 
        '''安裝說明: http://www.sharppoint.com.hk/cht/main/download_main.htm
        '''
        '''3. 登入平台
        '''安裝平台後，點擊桌面上的sptrader圖示後，根據以下所示登入平台。 
        ''' 
        '''網域: 220.241.155.37 
        '''使用者: 閣下的客戶編號 
        '''密碼: 請參閱此 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property textT() As String
            Get
                Return ResourceManager.GetString("textT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Please login by existing password].
        '''</summary>
        Friend ReadOnly Property useOldPwdE() As String
            Get
                Return ResourceManager.GetString("useOldPwdE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [请沿用旧密码].
        '''</summary>
        Friend ReadOnly Property useOldPwdS() As String
            Get
                Return ResourceManager.GetString("useOldPwdS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [請沿用舊密碼].
        '''</summary>
        Friend ReadOnly Property useOldPwdT() As String
            Get
                Return ResourceManager.GetString("useOldPwdT", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
